import asyncio
import json
import os
import uuid
from datetime import datetime
from typing import Dict, Any, List, Optional
from .normalizer.schema import Finding, PipelineRun
from .runners.sast_runner import run_semgrep
from .runners.sca_runner import run_sca
from .runners.iac_runner import run_iac, has_iac_files
from .runners.container_runner import run_container, has_dockerfile
from .runners.zap_runner import run_zap_dast
from .runners.cspm_runner import run_cspm
try:
    import database
except ImportError:
    from backend import database

REPORTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "reports_generated")
os.makedirs(REPORTS_DIR, exist_ok=True)

def generate_sarif_report(findings: List[Finding], run_id: str) -> str:
    """Generates standard SARIF v2.1.0 output for GitHub Security integration."""
    rules = []
    results = []
    rule_indices = {}

    for idx, f in enumerate(findings):
        rule_id = f"{f.tool.upper()}-{f.cwe or f.cve or 'SEC'}"
        if rule_id not in rule_indices:
            rule_indices[rule_id] = len(rules)
            rules.append({
                "id": rule_id,
                "name": f.title,
                "shortDescription": {"text": f.title},
                "fullDescription": {"text": f.description},
                "help": {"text": f.remediation or "Review and fix vulnerability."},
                "properties": {"tags": [f.source, f.tool, f.severity]}
            })

        results.append({
            "ruleId": rule_id,
            "ruleIndex": rule_indices[rule_id],
            "level": "error" if f.severity in ["critical", "high"] else "warning" if f.severity == "medium" else "note",
            "message": {"text": f.description},
            "locations": [{
                "physicalLocation": {
                    "artifactLocation": {"uri": f.file_path or f.endpoint or "project"},
                    "region": {"startLine": f.line or 1}
                }
            }]
        })

    sarif_doc = {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "VulnScan DevSecOps Engine",
                    "version": "2.5.0",
                    "rules": rules
                }
            },
            "results": results
        }]
    }

    file_path = os.path.join(REPORTS_DIR, f"findings_{run_id}.sarif")
    with open(file_path, "w", encoding="utf-8") as out:
        json.dump(sarif_doc, out, indent=2)
    return file_path

def generate_markdown_report(findings: List[Finding], run_id: str, repo_name: str = "Target Repository") -> str:
    """Generates a professional Markdown security report suitable for PR commit-back."""
    lines = [
        f"# 🛡️ VulnScan DevSecOps Pipeline Security Report",
        f"**Repository:** `{repo_name}` | **Scan Run ID:** `{run_id}` | **Generated:** `{datetime.utcnow().isoformat()} UTC`",
        "",
        "## Executive Findings Summary",
        f"- **Total Security Findings:** {len(findings)}",
        f"- **Critical Severity:** {sum(1 for f in findings if f.severity == 'critical')}",
        f"- **High Severity:** {sum(1 for f in findings if f.severity == 'high')}",
        f"- **Medium Severity:** {sum(1 for f in findings if f.severity == 'medium')}",
        f"- **Low / Info:** {sum(1 for f in findings if f.severity in ['low', 'info'])}",
        "",
        "## Detailed Findings Table",
        "| ID | Source | Tool | Severity | CWE / CVE | Finding Title | Location | Remediation |",
        "|---|---|---|---|---|---|---|---|"
    ]

    for f in findings:
        loc = f"{f.file_path}:{f.line}" if f.file_path else (f.endpoint or "Global")
        lines.append(f"| `{f.id}` | {f.source.upper()} | {f.tool} | **{f.severity.upper()}** | {f.cwe or f.cve or '-'} | {f.title} | `{loc}` | {f.remediation or '-'} |")

    lines.extend([
        "",
        "---",
        "*Automated scan report generated by VulnScan DevSecOps Engine. Human review recommended before production deployment.*"
    ])

    file_path = os.path.join(REPORTS_DIR, f"SECURITY_REPORT_{run_id}.md")
    with open(file_path, "w", encoding="utf-8") as out:
        out.write("\n".join(lines))
    return file_path

import re
import shutil

async def clone_or_pull_repo(github_target: str, run_id: str) -> str:
    """
    Clones the target GitHub repo into a dedicated workspace directory using shallow git clone.
    If github_target is already a local path, returns it directly.
    """
    if github_target and os.path.exists(github_target):
        return os.path.abspath(github_target)

    if not github_target:
        return os.getcwd()

    # Normalize URL
    if not github_target.startswith("http"):
        url = f"https://github.com/{github_target.strip('/')}.git"
    else:
        url = github_target if github_target.endswith(".git") else f"{github_target}.git"

    clean_name = re.sub(r'[^a-zA-Z0-9_-]', '_', github_target.replace("https://github.com/", "").replace(".git", ""))
    base_ws = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "scanner-app", "backend", "workspace"))
    os.makedirs(base_ws, exist_ok=True)
    workspace_dir = os.path.join(base_ws, f"{clean_name}_{run_id}")

    git_bin = shutil.which("git")
    if git_bin:
        try:
            proc = await asyncio.create_subprocess_exec(
                git_bin, "clone", "--depth", "1", url, workspace_dir,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            await asyncio.wait_for(proc.communicate(), timeout=120)
            if os.path.exists(workspace_dir):
                return workspace_dir
        except Exception as e:
            print(f"[Git Clone Warning]: {e}")

    return os.getcwd()

async def run_devsecops_pipeline(
    run_id: str,
    repo_id: Optional[int] = None,
    repo_path: Optional[str] = None,
    target_url: Optional[str] = None,
    options: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Executes the multi-lane DevSecOps pipeline DAG.
    1. Automated Repo Clone from GitHub URL / local path
    2. Concurrent Static Lane: SAST + SCA + IaC
    3. Container Image Scan (if Dockerfile present)
    4. DAST Web Application Scan (if target URL configured)
    5. CSPM Cloud Posture (if cloud options enabled)
    """
    options = options or {}
    database.update_pipeline_run(run_id, status="running", current_stage="cloning_repository")

    # Automated Clone / Pull
    target_repo = repo_path or options.get("repo_name")
    resolved_path = await clone_or_pull_repo(target_repo, run_id)
    target_url = target_url or "http://localhost:3000"

    database.update_pipeline_run(run_id, current_stage="static_analysis")

    all_findings: List[Finding] = []
    stages_status = {}

    # --- 1. Concurrent Static Analysis Lane ---
    t0 = datetime.utcnow()
    sast_task = run_semgrep(resolved_path, run_id, repo_id)
    sca_task = run_sca(resolved_path, run_id, repo_id)
    iac_task = run_iac(resolved_path, run_id, repo_id) if has_iac_files(resolved_path) else None

    results = await asyncio.gather(
        sast_task,
        sca_task,
        *( [iac_task] if iac_task else [] )
    )

    sast_findings = results[0]
    sca_findings, sbom_comps = results[1]
    iac_findings = results[2] if iac_task else []

    all_findings.extend(sast_findings)
    all_findings.extend(sca_findings)
    all_findings.extend(iac_findings)

    # Persist SBOM components
    if sbom_comps:
        database.add_sbom_components([c.dict() for c in sbom_comps], run_id, repo_id)

    stages_status["sast"] = {"status": "passed", "findings": len(sast_findings)}
    stages_status["sca"] = {"status": "passed", "findings": len(sca_findings), "sbom_count": len(sbom_comps)}
    stages_status["iac"] = {"status": "passed" if iac_task else "skipped", "findings": len(iac_findings)}

    # --- 2. Container Scan Lane ---
    database.update_pipeline_run(run_id, current_stage="container_scan")
    container_findings = await run_container(repo_path, run_id, repo_id)
    all_findings.extend(container_findings)
    stages_status["container"] = {"status": "passed", "findings": len(container_findings)}

    # --- 3. DAST Lane ---
    if options.get("enable_dast", True):
        database.update_pipeline_run(run_id, current_stage="dast_scan")
        dast_findings = await run_zap_dast(target_url, run_id, environment=options.get("environment", "staging"), repo_id=repo_id)
        all_findings.extend(dast_findings)
        stages_status["dast"] = {"status": "passed", "findings": len(dast_findings)}

    # --- 4. CSPM Lane ---
    if options.get("enable_cspm", False):
        database.update_pipeline_run(run_id, current_stage="cspm_scan")
        cspm_findings = await run_cspm(provider=options.get("cloud_provider", "aws"), run_id=run_id, repo_id=repo_id)
        all_findings.extend(cspm_findings)
        stages_status["cspm"] = {"status": "passed", "findings": len(cspm_findings)}

    # --- 5. Persist All Unified Findings to Database ---
    for f in all_findings:
        database.add_unified_finding(f.dict())

    # --- 6. Generate SARIF & Markdown Reports ---
    sarif_path = generate_sarif_report(all_findings, run_id)
    markdown_path = generate_markdown_report(all_findings, run_id, options.get("repo_name", "Target Repository"))

    summary = {
        "total_findings": len(all_findings),
        "critical": sum(1 for f in all_findings if f.severity == "critical"),
        "high": sum(1 for f in all_findings if f.severity == "high"),
        "medium": sum(1 for f in all_findings if f.severity == "medium"),
        "low": sum(1 for f in all_findings if f.severity in ["low", "info"]),
        "sarif_report": sarif_path,
        "markdown_report": markdown_path
    }

    database.update_pipeline_run(
        run_id,
        status="completed",
        current_stage="complete",
        stages=stages_status,
        summary=summary,
        sarif_path=sarif_path,
        markdown_report_path=markdown_path,
        completed=True
    )

    return {
        "run_id": run_id,
        "status": "completed",
        "stages": stages_status,
        "summary": summary,
        "findings_count": len(all_findings)
    }
